'use strict';

(function(self) {
	/**
	* SUCCESS HTTP STATUS
	**/
	self.HTTP_STATUS_SUCCESS = 200;
	self.HTTP_STATUS_CREATED = 201;
	self.HTTP_STATUS_ACCEPTED = 202;

	/**
	* ERROR HANDLER HTTP STATUS
	**/
	self.HTTP_STATUS_BAD_REQUEST = 400;
	self.HTTP_STATUS_UNAUTHORIZED = 401;
	self.HTTP_STATUS_FORBIDDEN = 403;
	self.HTTP_STATUS_NOT_FOUND = 404;
	self.HTTP_STATUS_METHOD_NOT_ALLOWED = 405;
	self.HTTP_STATUS_NOT_ACCEPTABLE = 406;
	self.HTTP_STATUS_CONFLICT = 409;
})(this);